MODULES+=	http-proxy-connect

MODULE_SUMMARY_http_proxy_connect=	A forward proxy module for CONNECT request handling

include $(CONTRIB)/src/ngx_http_proxy_connect_module/version

MODULE_VERSION_http_proxy_connect=	$(HTTP_PROXY_CONNECT_MODULE_VERSION)
MODULE_RELEASE_http_proxy_connect=	1

MODULE_VERSION_PREFIX_http_proxy_connect=$(MODULE_TARGET_PREFIX)

MODULE_SOURCES_http_proxy_connect=	ngx_http_proxy_connect_module-$(HTTP_PROXY_CONNECT_MODULE_VERSION).tar.gz

MODULE_CONFARGS_http_proxy_connect=	--add-dynamic-module=$(MODSRC_PREFIX)ngx_http_proxy_connect_module-$(HTTP_PROXY_CONNECT_MODULE_VERSION)

.deps-module-http_proxy_connect:
	cd $(CONTRIB) && make .sum-ngx_http_proxy_connect_module
	touch $@

prerequisites-for-module-http_proxy_connect:

MODULE_BUILD_DEPENDS_http_proxy_connect=

define MODULE_POST_http_proxy_connect
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_http_proxy_connect) for $(MODULE_SUMMARY_PREFIX) have been installed.
To enable these modules, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_http_proxy_connect_module.so;

Please refer to the module documentation for further details:
https://github.com/leev/ngx_http_proxy_connect_module

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_http_proxy_connect
